// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3UAyPGAwuTOLO51zhwUun_NuUl1TV8kg',
    appId: '1:81112551118:android:8579cebf340fceba110a9f',
    messagingSenderId: '81112551118',
    projectId: 'recipe-app-6e080',
    databaseURL: 'https://recipe-app-6e080-default-rtdb.firebaseio.com',
    storageBucket: 'recipe-app-6e080.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBO_l0C58L6MzB6N3NOBxO8G-ml4eK5U9Q',
    appId: '1:81112551118:ios:0ead73329243ce4c110a9f',
    messagingSenderId: '81112551118',
    projectId: 'recipe-app-6e080',
    databaseURL: 'https://recipe-app-6e080-default-rtdb.firebaseio.com',
    storageBucket: 'recipe-app-6e080.appspot.com',
    iosBundleId: 'com.example.recipeApp',
  );
}
